"""add outbox and idempotency

Revision ID: ceac11bd0752
Revises: b2c4e8f1a903
Create Date: 2026-06-30 10:15:09.065663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ceac11bd0752'
down_revision: Union[str, Sequence[str], None] = 'b2c4e8f1a903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('TICKET_PURCHASED', name='outbox_event_type', native_enum=False), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', name='outbox_event_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_pending_created_at', 'outbox', ['created_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('idempotency',
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('request_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('idempotency_key'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.alter_column('events', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('new', 'published', 'cancelled', 'registration_closed', 'finished', name='event_status', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'status',
               existing_type=sa.Enum('new', 'published', 'cancelled', 'registration_closed', 'finished', name='event_status', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_table('idempotency')
    op.drop_index('ix_outbox_pending_created_at', table_name='outbox', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('outbox')
    # ### end Alembic commands ###
